# Generated by Django 4.0.3 on 2022-03-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='youtube_id',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
